name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn docs:build
      - run: echo 'note.raindays.cn' > CNAME
      - name: Deploy melody-core.github.io/master
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY  }}
          EXTERNAL_REPOSITORY: melody-core/melody-core.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: docs/.vuepress/dist
        with:
          emptyCommits: false
